framework:
    validation:
        email_validation_mode: html5
        enable_annotations: true

        # Vous pouvez activer l'auto-mapping ici si nécessaire
        # auto_mapping:
        #     App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
